{% set version = "6.2.9" %}

package:
  name: bsddb3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bsddb3/bsddb3-{{ version }}.tar.gz
  sha256: 70d05ec8dc568f42e70fc919a442e0daadc2a905a1cfb7ca77f549d49d6e7801

build:
  number: 1
  script: |
    export YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION=1  # [not win]
    export BERKELEYDB_DIR=$PREFIX                                  # [not win]
    set YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION=1     # [win]
    set BERKELEYDB_INCDIR=%LIBRARY_INC%                            # [win]
    set BERKELEYDB_LIBDIR=%LIBRARY_LIB%                            # [win]
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libdb
  run:
    - python
    - libdb

test:
  imports:
    - bsddb3

about:
  home: https://www.jcea.es/programacion/pybsddb.htm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python bindings for Oracle Berkeley DB

  description: |
    This module provides a nearly complete wrapping of the Oracle/Sleepycat C API for the Database Environment, 
    Database, Cursor, Log Cursor, Sequence and Transaction objects, 
    and each of these is exposed as a Python type in the bsddb3.db module. 
    The database objects can use various access methods: btree, hash, recno, and queue. 
    Complete support of Berkeley DB distributed transactions. 
    Complete support for Berkeley DB Replication Manager. 
    Complete support for Berkeley DB Base Replication. Support for RPC.
  doc_url: https://www.jcea.es/programacion/pybsddb_doc/
  dev_url: https://hg.jcea.es/pybsddb/

extra:
  recipe-maintainers:
    - shadowwalkersb
